sudo: false

language: ruby

services:
  - docker

env:
  - VERSION=3.5
  - VERSION=3.6

script:
  - mkdir packages
  - docker run -v $(pwd):/home/builder/package -v $(pwd)/packages:/packages -e RSA_PUBLIC_KEY="$RSA_PUBLIC_KEY" -e RSA_PRIVATE_KEY="$RSA_PRIVATE_KEY" msales/alpine-build:$VERSION

before_deploy:
  - sudo chown -R travis:travis ./

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_ACCESS_SECRET
  region: $S3_REGION
  bucket: $S3_BUCKET
  local_dir: packages
  upload-dir: $VERSION
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always